# Generated by Django 4.2.30 on 2026-08-30 17:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='district name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='district code')),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100, verbose_name='state')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='mandal name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='mandal code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('headquarters', models.CharField(blank=True, max_length=100, verbose_name='headquarters')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='contact person')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandals', to='api.district')),
            ],
            options={
                'verbose_name': 'mandal',
                'verbose_name_plural': 'mandals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MandalEducationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='employee ID')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='qualification')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='experience years')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='office location')),
                ('office_phone', models.CharField(blank=True, max_length=20, verbose_name='office phone')),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meos', to='api.mandal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meo_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mandal education officer',
                'verbose_name_plural': 'mandal education officers',
            },
        ),
        migrations.CreateModel(
            name='StateEducationOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state_official_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'state education official',
                'verbose_name_plural': 'state education officials',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='school name')),
                ('school_code', models.CharField(max_length=20, unique=True, verbose_name='school code')),
                ('address', models.TextField(verbose_name='address')),
                ('school_type', models.CharField(default='secondary', max_length=50, verbose_name='school type')),
                ('principal_name', models.CharField(blank=True, max_length=100, verbose_name='principal name')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='contact person')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='established year')),
                ('total_teachers', models.PositiveIntegerField(default=0, verbose_name='total teachers')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='total students')),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='api.mandal')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'ordering': ['name'],
                'unique_together': {('mandal', 'school_code')},
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='permissions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platform admin',
                'verbose_name_plural': 'platform admins',
            },
        ),
        migrations.CreateModel(
            name='Headmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='qualification')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='experience years')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='joining date')),
                ('is_current', models.BooleanField(default=True, verbose_name='is current')),
                ('awards', models.TextField(blank=True, verbose_name='awards')),
                ('achievements', models.TextField(blank=True, verbose_name='achievements')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headmaster', to='api.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headmaster_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'headmaster',
                'verbose_name_plural': 'headmasters',
            },
        ),
        migrations.CreateModel(
            name='DistrictEducationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='employee ID')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='qualification')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='experience years')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deos', to='api.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deo_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'district education officer',
                'verbose_name_plural': 'district education officers',
            },
        ),
        migrations.CreateModel(
            name='ResultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022')], max_length=4, verbose_name='academic year')),
                ('total_students_appeared', models.PositiveIntegerField(verbose_name='total students appeared')),
                ('students_meeting_threshold', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='students meeting threshold')),
                ('threshold_value', models.PositiveIntegerField(help_text='e.g., 500 out of 600', verbose_name='threshold value')),
                ('extra_credit_points', models.PositiveIntegerField(default=0, verbose_name='extra credit points')),
                ('extra_credit_details', models.TextField(blank=True, verbose_name='extra credit details')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='reviewer comment')),
                ('qualifying_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated: (students_meeting_threshold / total_students_appeared) × 100', max_digits=5, null=True, verbose_name='qualifying percentage')),
                ('headmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='api.headmaster')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='api.mandaleducationofficer')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='api.school')),
            ],
            options={
                'verbose_name': 'result submission',
                'verbose_name_plural': 'result submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=4, verbose_name='academic year')),
                ('qualifying_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='qualifying percentage')),
                ('mandal_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='mandal rank')),
                ('district_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='district rank')),
                ('state_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='state rank')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='computed at')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.school')),
            ],
            options={
                'verbose_name': 'ranking snapshot',
                'verbose_name_plural': 'ranking snapshots',
                'ordering': ['academic_year', 'mandal_rank'],
                'unique_together': {('school', 'academic_year')},
            },
        ),
    ]
